image: docker:latest

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification"
  only:
    - master
  tags:
    - shell

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - shell

kfp-deploy:
  stage: deploy
  before_script:
    - pip3 install --no-cache --upgrade pip setuptools
    - pip3 install kfp
  script:
    - docker pull "$CI_REGISTRY_IMAGE/pytorch_image_classification"
    - python3 run_pipeline.py --docker-image "$CI_REGISTRY_IMAGE/pytorch_image_classification"
  only:
    - master
  tags:
    - shell
