image: docker:latest

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification"
  only:
    - master
  tags:
    - shell

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - shell
