image: docker:latest

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification"
  only:
    - master
  tags:
    - shell

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/pytorch_image_classification:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - shell

kfp-deploy:
  image: python:latest
  variables:
    GIT_SSL_NO_VERIFY: 1
  stage: deploy
  before_script:
    - python3 -m ensurepip
    - python3 -m pip install --no-cache --upgrade pip setuptools
    - python3 -m pip install kfp
  script:
    - python3 run_pipeline.py --docker-image "$CI_REGISTRY_IMAGE/pytorch_image_classification"
  only:
    - master
  tags:
    - docker
